In [1]:
import pandas as pd
import numpy as np

In [2]:
df_nykaa = pd.read_csv('nykaa_campaign_data_with_nulls.csv', encoding='latin1')

In [3]:
df_purplle = pd.read_csv('purplle_campaign_data_with_nulls.csv', encoding='latin1')

In [4]:
df_tira = pd.read_csv('tira_campaign_data_with_nulls.csv', encoding='latin1')

In [5]:
df_nykaa

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21.0,"WhatsApp, YouTube",57804.0,6156.0,3616.0,2355.0,1867515.0,NaN,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18.0,YouTube,91801.0,3321.0,1971.0,1357.0,1046247.0,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23.0,"WhatsApp, Google, YouTube",15536.0,2182.0,952.0,755.0,197055.0,90.60,NaN,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18.0,"YouTube, Facebook, Instagram",88114.0,8413.0,2231.0,947.0,376906.0,249.07,0.60,Hindi,13.15,NaN,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10.0,"Facebook, Instagram",96871.0,3743.0,2060.0,1258.0,518296.0,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55550,NY-CMP-56550,SEO,Youth,16.0,"Instagram, Email",31041.0,3849.0,1012.0,639.0,162945.0,374.90,-0.32,Tamil,17.72,Tier 2 City Customers,16-02-2025
55551,NY-CMP-56551,Paid Ads,Tier 2 City Customers,26.0,Facebook,27335.0,3715.0,2184.0,1006.0,792728.0,56.38,12.98,English,25.26,Premium Shoppers,18-11-2024
55552,NY-CMP-56552,Influencer,Tier 2 City Customers,23.0,NaN,43481.0,6447.0,3751.0,1668.0,383640.0,56.18,3.09,Bengali,27.29,Working Women,24-10-2024
55553,NY-CMP-56553,Social Media,College Students,16.0,"Facebook, Email",NaN,2518.0,584.0,299.0,194051.0,227.53,1.85,Bengali,10.14,Working Women,22-05-2025
55554,NY-CMP-56554,Social Media,College Students,25.0,"YouTube, Instagram, WhatsApp",41096.0,5254.0,2570.0,1894.0,647748.0,35.11,8.74,English,23.65,College Students,30-05-2025

In [6]:
df_purplle

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,PU-CMP-1000,Paid Ads,Working Women,6.0,"Facebook, Google",31869.0,3490.0,1946.0,902.0,493394.0,55.93,8.78,Tamil,19.89,Premium Shoppers,27-12-2024
1,PU-CMP-1001,Paid Ads,Premium Shoppers,8.0,"Instagram, WhatsApp",26640.0,2441.0,741.0,314.0,108644.0,197.44,0.75,Bengali,13.12,NaN,26-11-2024
2,PU-CMP-1002,Influencer,Youth,22.0,"Facebook, WhatsApp",36967.0,4997.0,1025.0,653.0,NaN,234.59,0.56,NaN,18.06,College Students,08-01-2025
3,PU-CMP-1003,Paid Ads,Youth,15.0,"Instagram, WhatsApp",73258.0,5893.0,2565.0,1970.0,1341570.0,103.76,5.56,Bengali,14.23,College Students,14-03-2025
4,PU-CMP-1004,Social Media,Premium Shoppers,11.0,"WhatsApp, Instagram",91081.0,6393.0,3282.0,2582.0,787510.0,78.61,NaN,English,13.46,College Students,11-07-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55550,PU-CMP-56550,SEO,Premium Shoppers,10.0,"WhatsApp, Instagram",58191.0,7763.0,3471.0,2132.0,1097980.0,73.52,6.00,Tamil,22.97,Youth,08-05-2025
55551,PU-CMP-56551,Email,Tier 2 City Customers,12.0,"YouTube, Google",85085.0,8986.0,4096.0,2308.0,800876.0,53.17,5.53,Tamil,18.09,College Students,23-08-2024
55552,PU-CMP-56552,Email,College Students,29.0,"YouTube, Google, Email",66094.0,4051.0,2155.0,1307.0,414319.0,113.10,1.80,Bengali,NaN,NaN,09-11-2024
55553,PU-CMP-56553,Paid Ads,College Students,7.0,"Facebook, WhatsApp",65050.0,5196.0,2263.0,1235.0,737295.0,237.80,NaN,Hindi,13.37,Youth,30-09-2024
55554,PU-CMP-56554,Social Media,College Students,25.0,"Facebook, Instagram, Email",19137.0,1529.0,512.0,303.0,154227.0,252.94,1.01,Hindi,12.25,Premium Shoppers,04-11-2024

In [7]:
df_tira

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,TI-CMP-1000,SEO,Working Women,11.0,NaN,64004.0,2906.0,1639.0,952.0,222768.0,129.72,0.80,Tamil,NaN,Premium Shoppers,30-10-2024
1,TI-CMP-1001,Social Media,Tier 2 City Customers,24.0,YouTube,71795.0,2051.0,552.0,256.0,199168.0,316.36,1.46,Tamil,3.98,College Students,11-09-2024
2,TI-CMP-1002,NaN,Working Women,28.0,NaN,79158.0,3546.0,1928.0,1314.0,433620.0,NaN,2.62,English,8.58,Tier 2 City Customers,28-08-2024
3,TI-CMP-1003,Email,Youth,8.0,Google,31523.0,3721.0,2088.0,736.0,571872.0,161.13,3.82,Bengali,20.76,Youth,27-07-2024
4,TI-CMP-1004,Paid Ads,Premium Shoppers,15.0,"Facebook, Email, WhatsApp",61441.0,7277.0,3615.0,2602.0,1477936.0,82.07,NaN,Tamil,21.96,College Students,19-12-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55550,NaN,NaN,Tier 2 City Customers,11.0,"Instagram, YouTube, Email",NaN,3799.0,NaN,1099.0,454986.0,213.21,0.94,Bengali,10.70,Youth,12-11-2024
55551,TI-CMP-56551,SEO,Working Women,20.0,"Google, Instagram",54886.0,1578.0,634.0,NaN,136514.0,436.24,-0.09,English,4.66,Working Women,25-08-2024
55552,TI-CMP-56552,Email,NaN,13.0,"Facebook, Instagram",97954.0,11480.0,4567.0,2144.0,445952.0,78.77,1.64,NaN,18.57,Premium Shoppers,15-04-2025
55553,NaN,Influencer,Premium Shoppers,22.0,"Google, Email",11669.0,NaN,122.0,44.0,26884.0,NaN,-0.76,English,5.35,Working Women,21-07-2024
55554,TI-CMP-56554,Paid Ads,Working Women,NaN,Instagram,50497.0,1604.0,542.0,363.0,281688.0,151.44,4.12,English,4.97,Premium Shoppers,02-05-2025

In [8]:
df_all = pd.concat([df_nykaa, df_purplle, df_tira], ignore_index=True)

In [9]:
df_all.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21.0,"WhatsApp, YouTube",57804.0,6156.0,3616.0,2355.0,1867515.0,NaN,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18.0,YouTube,91801.0,3321.0,1971.0,1357.0,1046247.0,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23.0,"WhatsApp, Google, YouTube",15536.0,2182.0,952.0,755.0,197055.0,90.60,NaN,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18.0,"YouTube, Facebook, Instagram",88114.0,8413.0,2231.0,947.0,376906.0,249.07,0.60,Hindi,13.15,NaN,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10.0,"Facebook, Instagram",96871.0,3743.0,2060.0,1258.0,518296.0,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024

In [9]:
df_all.shape

(166665, 16)

In [10]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166665 entries, 0 to 166664
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Campaign_ID       161248 non-null  object
 1   Campaign_Type     158307 non-null  object
 2   Target_Audience   158493 non-null  object
 3   Duration          158342 non-null  float64
 4   Channel_Used      158383 non-null  object
 5   Impressions       158441 non-null  float64
 6   Clicks            158441 non-null  float64
 7   Leads             158575 non-null  float64
 8   Conversions       158665 non-null  float64
 9   Revenue           158361 non-null  float64
 10  Acquisition_Cost  158504 non-null  float64
 11  ROI               158367 non-null  float64
 12  Language          158366 non-null  object
 13  Engagement_Score  158584 non-null  float64
 14  Customer_Segment  158490 non-null  object
 15  Date              158566 non-null  object
dtypes: float64(9), object(7)
memory usage: 20.3+ MB

In [11]:
df_all.isnull().sum()

Campaign_ID         5417
Campaign_Type       8358
Target_Audience     8172
Duration            8323
Channel_Used        8282
Impressions         8224
Clicks              8224
Leads               8090
Conversions         8000
Revenue             8304
Acquisition_Cost    8161
ROI                 8298
Language            8299
Engagement_Score    8081
Customer_Segment    8175
Date                8099
dtype: int64

In [12]:
df_all.describe()

,Duration,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Engagement_Score
count,158342.000000,158441.000000,158441.000000,158575.000000,158665.000000,1.583610e+05,158504.000000,158367.00000,158584.000000
mean,17.488582,55068.759456,4684.973978,1872.167157,1028.498213,5.138267e+05,376.830560,2.69620,13.764843
std,7.501765,25961.688169,3177.355919,1430.272768,857.687806,4.875933e+05,536.701697,4.48544,6.328162
min,5.000000,10001.000000,202.000000,48.000000,17.000000,3.895000e+03,8.180000,-0.99000,2.560000
25%,11.000000,32599.000000,2110.000000,779.000000,401.000000,1.775800e+05,106.760000,0.05000,8.380000
50%,17.000000,55113.000000,3908.000000,1476.000000,775.000000,3.588720e+05,208.725000,1.24000,13.590000
75%,24.000000,77582.000000,6695.000000,2600.000000,1403.000000,6.856400e+05,428.560000,3.58000,18.790000
max,30.000000,100000.000000,14944.000000,8876.000000,6686.000000,4.579910e+06,15473.160000,79.30000,30.990000

In [13]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

# Select only your numeric columns
num_cols = ['Duration', 'Impressions', 'Clicks', 'Leads', 'Conversions', 'Revenue', 'Acquisition_Cost', 'ROI', 'Engagement_Score']

# Initialize the imputer (it uses Bayesian Ridge regression by default)
imputer = IterativeImputer(random_state=42, max_iter=10)

# Fit and transform the numeric data
df_all[num_cols] = imputer.fit_transform(df_all[num_cols])

In [14]:
df_all.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21.0,"WhatsApp, YouTube",57804.0,6156.0,3616.0,2355.0,1867515.0,162.31857,6.140000,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18.0,YouTube,91801.0,3321.0,1971.0,1357.0,1046247.0,180.83000,3.260000,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23.0,"WhatsApp, Google, YouTube",15536.0,2182.0,952.0,755.0,197055.0,90.60000,0.194711,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18.0,"YouTube, Facebook, Instagram",88114.0,8413.0,2231.0,947.0,376906.0,249.07000,0.600000,Hindi,13.15,NaN,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10.0,"Facebook, Instagram",96871.0,3743.0,2060.0,1258.0,518296.0,228.60000,0.800000,Hindi,7.29,Tier 2 City Customers,29-12-2024

In [15]:
df_all.isnull().sum()

Campaign_ID         5417
Campaign_Type       8358
Target_Audience     8172
Duration               0
Channel_Used        8282
Impressions            0
Clicks                 0
Leads                  0
Conversions            0
Revenue                0
Acquisition_Cost       0
ROI                    0
Language            8299
Engagement_Score       0
Customer_Segment    8175
Date                8099
dtype: int64

In [16]:
df_all.dropna()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21.000000,"WhatsApp, YouTube",57804.0,6156.000000,3616.0,2355.000000,1867515.0,162.31857,6.140000,Hindi,20.980000,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18.000000,YouTube,91801.0,3321.000000,1971.0,1357.000000,1046247.0,180.83000,3.260000,Hindi,7.240000,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23.000000,"WhatsApp, Google, YouTube",15536.0,2182.000000,952.0,755.000000,197055.0,90.60000,0.194711,English,25.030000,College Students,14-01-2025
4,NY-CMP-1004,Paid Ads,College Students,10.000000,"Facebook, Instagram",96871.0,3743.000000,2060.0,1258.000000,518296.0,228.60000,0.800000,Hindi,7.290000,Tier 2 City Customers,29-12-2024
6,NY-CMP-1006,Paid Ads,College Students,21.000000,"YouTube, Google, WhatsApp",82267.0,5458.378102,1873.0,1386.000000,633402.0,210.17000,1.170000,Tamil,9.906739,Youth,01-09-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166655,TI-CMP-56545,Social Media,College Students,7.000000,"Facebook, Instagram, YouTube",78207.0,3086.000000,883.0,620.000000,199020.0,362.11000,-0.110000,English,5.870000,College Students,01-03-2025
166656,TI-CMP-56546,Social Media,Premium Shoppers,14.000000,Instagram,38933.0,2683.000000,1307.0,931.000000,641459.0,298.63000,1.310000,Hindi,13.857298,Premium Shoppers,25-09-2024
166658,TI-CMP-56548,Influencer,Premium Shoppers,15.000000,"WhatsApp, YouTube, Google",25929.0,1388.000000,808.0,567.000000,408240.0,258.43000,1.790000,Hindi,10.660000,Working Women,19-05-2025
166661,TI-CMP-56551,SEO,Working Women,20.000000,"Google, Instagram",54886.0,1578.000000,634.0,296.082674,136514.0,436.24000,-0.090000,English,4.660000,Working Women,25-08-2024
166664,TI-CMP-56554,Paid Ads,Working Women,17.493552,Instagram,50497.0,1604.000000,542.0,363.000000,281688.0,151.44000,4.120000,English,4.970000,Premium Shoppers,02-05-2025

In [17]:
df_all.describe()

,Duration,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Engagement_Score
count,166665.000000,166665.000000,166665.000000,166665.000000,166665.000000,1.666650e+05,166665.000000,166665.000000,166665.000000
mean,17.488619,55061.703537,4682.418828,1871.270677,1029.068062,5.137769e+05,376.698841,2.690807,13.764929
std,7.312058,25870.053825,3168.450780,1426.076118,855.813731,4.853881e+05,529.425143,4.441835,6.308307
min,5.000000,-65263.532257,-1824.770842,-454.040010,-259.949132,-7.357875e+04,-1586.833041,-12.388285,-24.040240
25%,11.000000,32932.000000,2119.000000,781.000000,402.000000,1.783340e+05,107.020000,0.060000,8.450000
50%,17.491840,55187.000000,3934.000000,1480.000000,778.000000,3.600960e+05,211.810000,1.250000,13.610000
75%,24.000000,77240.000000,6694.000000,2600.000000,1405.000000,6.859100e+05,437.590000,3.600000,18.720000
max,30.000000,128611.268236,15479.148469,8876.000000,6686.000000,4.579910e+06,15473.160000,79.300000,38.092649

In [18]:
# Commit to the clean, dropped dataset
df_all = df_all.dropna()

# Step 2: Fix the low-end negative artifacts created by the IterativeImputer
zero_floor_cols = ['Impressions', 'Clicks', 'Leads', 'Conversions', 'Revenue', 'Acquisition_Cost', 'Engagement_Score']
for col in zero_floor_cols:
    df_all[col] = df_all[col].clip(lower=0)

# ROI can legally be negative (loss), but clamp any weird imputer math below -1.0 (100% loss)
df_all['ROI'] = df_all['ROI'].clip(lower=-1.0)

# Step 3: Winsorize the extreme high-end spikes at the 99th percentile
skewed_cols = ['Revenue', 'Acquisition_Cost', 'ROI', 'Clicks', 'Leads', 'Conversions']
for col in skewed_cols:
    q_upper = df_all[col].quantile(0.99)
    df_all[col] = df_all[col].clip(upper=q_upper)

print("Preprocessing complete! Final clean dataset shape:", df_all.shape)

Preprocessing complete! Final clean dataset shape: (118955, 16)

In [19]:
df_all.describe()

,Duration,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Engagement_Score
count,118955.000000,118955.000000,118955.000000,118955.000000,118955.000000,1.189550e+05,118955.000000,118955.000000,118955.000000
mean,17.466198,55066.627120,4675.366522,1865.302566,1024.046591,5.097459e+05,364.107109,2.625297,13.768996
std,7.308295,25859.839243,3146.610991,1403.811363,834.118617,4.655323e+05,434.052454,3.992269,6.312428
min,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,-1.000000,0.000000
25%,11.000000,32892.000000,2117.000000,780.102472,401.000000,1.785050e+05,106.860000,0.060000,8.450000
50%,17.486497,55242.000000,3932.000000,1479.000000,778.000000,3.598440e+05,211.370000,1.260000,13.610000
75%,24.000000,77260.000000,6689.828973,2600.000000,1405.000000,6.862945e+05,436.495000,3.610000,18.730000
max,30.000000,128611.268236,13133.000000,6361.460000,3972.059861,2.328291e+06,2532.481200,20.994600,38.092649

In [20]:
# 1. Calculate Total Acquisition Cost
df_all['Total_Acquisition_Cost'] = df_all['Conversions'] * df_all['Acquisition_Cost']

# 2. Calculate Net Profit
df_all['Net_Profit'] = df_all['Revenue'] - df_all['Total_Acquisition_Cost']

# 3. Calculate True ROI (Adding 1e-5 to avoid division by zero)
df_all['ROI'] = df_all['Net_Profit'] / (df_all['Total_Acquisition_Cost'] + 1e-5)

# 4. Create Profit_Loss Target Column (1 for Profit, 0 for Loss)
df_all['Profit_Loss'] = (df_all['Net_Profit'] > 0).astype(int)

In [21]:
df_all

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date,Total_Acquisition_Cost,Net_Profit,Profit_Loss
0,NY-CMP-1000,Social Media,College Students,21.000000,"WhatsApp, YouTube",57804.0,6156.000000,3616.0,2355.000000,1867515.0,162.31857,3.885455,Hindi,20.980000,College Students,29-04-2025,382260.232841,1.485255e+06,1
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18.000000,YouTube,91801.0,3321.000000,1971.0,1357.000000,1046247.0,180.83000,3.263673,Hindi,7.240000,College Students,06-04-2025,245386.310000,8.008607e+05,1
2,NY-CMP-1002,Influencer,Youth,23.000000,"WhatsApp, Google, YouTube",15536.0,2182.000000,952.0,755.000000,197055.0,90.60000,1.880795,English,25.030000,College Students,14-01-2025,68403.000000,1.286520e+05,1
4,NY-CMP-1004,Paid Ads,College Students,10.000000,"Facebook, Instagram",96871.0,3743.000000,2060.0,1258.000000,518296.0,228.60000,0.802275,Hindi,7.290000,Tier 2 City Customers,29-12-2024,287578.800000,2.307172e+05,1
6,NY-CMP-1006,Paid Ads,College Students,21.000000,"YouTube, Google, WhatsApp",82267.0,5458.378102,1873.0,1386.000000,633402.0,210.17000,1.174430,Tamil,9.906739,Youth,01-09-2024,291295.620000,3.421064e+05,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166655,TI-CMP-56545,Social Media,College Students,7.000000,"Facebook, Instagram, YouTube",78207.0,3086.000000,883.0,620.000000,199020.0,362.11000,-0.113529,English,5.870000,College Students,01-03-2025,224508.200000,-2.548820e+04,0
166656,TI-CMP-56546,Social Media,Premium Shoppers,14.000000,Instagram,38933.0,2683.000000,1307.0,931.000000,641459.0,298.63000,1.307203,Hindi,13.857298,Premium Shoppers,25-09-2024,278024.530000,3.634345e+05,1
166658,TI-CMP-56548,Influencer,Premium Shoppers,15.000000,"WhatsApp, YouTube, Google",25929.0,1388.000000,808.0,567.000000,408240.0,258.43000,1.786054,Hindi,10.660000,Working Women,19-05-2025,146529.810000,2.617102e+05,1
166661,TI-CMP-56551,SEO,Working Women,20.000000,"Google, Instagram",54886.0,1578.000000,634.0,296.082674,136514.0,436.24000,0.056912,English,4.660000,Working Women,25-08-2024,129163.105647,7.350894e+03,1
166664,TI-CMP-56554,Paid Ads,Working Women,17.493552,Instagram,50497.0,1604.000000,542.0,363.000000,281688.0,151.44000,4.124142,English,4.970000,Premium Shoppers,02-05-2025,54972.720000,2.267153e+05,1

In [23]:
Cleaned_data = df_all.to_csv('Cleaned_data.csv', index=False)